# Generated by Django 6.0.4 on 2026-04-14 02:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgenciaTransporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej. SHALOM - Sede Centro', max_length=200, unique=True)),
                ('direccion', models.TextField(help_text='Dirección exacta de la agencia')),
                ('referencia', models.TextField(blank=True, help_text='Ej. Frente al parque, rejas verdes', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GuiaRemision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=200)),
                ('dni_ruc', models.CharField(max_length=11)),
                ('direccion', models.TextField()),
                ('producto', models.CharField(max_length=255)),
                ('celular', models.CharField(blank=True, max_length=20, null=True)),
                ('agencia', models.CharField(blank=True, max_length=200, null=True)),
                ('referencia', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
