# Generated by Django 6.0.4 on 2026-04-22 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guiaremision',
            name='dni_ruc',
            field=models.CharField(help_text='Ingrese 8 dígitos para DNI o 11 para RUC', max_length=11),
        ),
    ]
