# Generated by Django 6.0.4 on 2026-04-23 04:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_guiaremision_dni_ruc'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agenciatransporte',
            options={'ordering': ['nombre'], 'verbose_name': 'Agencia de Transporte', 'verbose_name_plural': 'Agencias de Transporte'},
        ),
        migrations.AlterModelOptions(
            name='guiaremision',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Guía de Remisión', 'verbose_name_plural': 'Guías de Remisión'},
        ),
        migrations.AlterField(
            model_name='guiaremision',
            name='agencia',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Agencia'),
        ),
        migrations.AlterField(
            model_name='guiaremision',
            name='celular',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='guiaremision',
            name='cliente',
            field=models.CharField(max_length=200, verbose_name='Nombre del Cliente'),
        ),
        migrations.AlterField(
            model_name='guiaremision',
            name='direccion',
            field=models.TextField(verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='guiaremision',
            name='dni_ruc',
            field=models.CharField(help_text='Ingrese 8 dígitos para DNI o 11 para RUC', max_length=11, verbose_name='DNI/RUC'),
        ),
        migrations.AlterField(
            model_name='guiaremision',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='guiaremision',
            name='producto',
            field=models.CharField(max_length=255, verbose_name='Producto (Categoría)'),
        ),
        migrations.AlterField(
            model_name='guiaremision',
            name='referencia',
            field=models.TextField(blank=True, null=True, verbose_name='Referencia'),
        ),
        migrations.AlterField(
            model_name='guiaremision',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
