# Generated by Django 6.0.4 on 2026-05-06 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_agenciatransporte_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenciatransporte',
            name='ubicacion',
            field=models.CharField(blank=True, help_text='Ej. Lima / Lima / San Juan De Lurigancho / Av Santa Rosa', max_length=255, null=True, verbose_name='Ubicación (Dep/Prov/Dist)'),
        ),
    ]
