# Generated by Django 6.0.4 on 2026-05-09 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_agenciatransporte_ubicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='guiaremision',
            name='ubigeo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ubigeo'),
        ),
    ]
