# Generated by Django 6.0.4 on 2026-05-10 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_guiaremision_ubigeo'),
    ]

    operations = [
        migrations.AddField(
            model_name='guiaremision',
            name='fecha_edicion',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
